- hosts: tomcat
  become: true
  vars_files:
    - credentials.var
  tasks:
    - name: check whether the file exist:
      stat:
        path: /opt/tomcat/webapps/Example-{{ ArtifactVersion }}.war
      register: exist  
    - name: msg when exist
      debug:
        msg:"exist version"
      when: exist.stat == True 
    - name: JFrogArtifactToHosttemp
      maven_artifact:
        group_id: com.github.Premvikash
        artifact_id: Example
        extension: war
        version: "{{ ArtifactVersion }}"
        repository_url: "http://3.109.139.250:8081/artifactory/libs-snapshot-local/"
        username: "{{ Username }}" 
        password: "{{ Password }}"
        dest: /tmp/Example-{{ ArtifactVersion }}.war
        mode: '0644'
    - name: Deploy in tomcat
      copy:
        src: /tmp/Example-{{ ArtifactVersion }}.war
        dest: /opt/tomcat/webapps
        remote_src: yes
        mode: 0777
    
