- hosts: tomcat
  become: true
  vars_files:
    - credentials.var
  tasks:
    - name: remove war file from temp folder
      shell: rm -rf /tmp/Example-{{ ArtifactVersion }}.war
    - name: JFrogArtifactToHosttemp
      maven_artifact:
        group_id: com.github.Premvikash
        artifact_id: Example
        extension: war
        version: {{ ArtifactVersion }}
        repository_url: "http://3.109.139.250:8081/artifactory/libs-snapshot-local/"
        username: "{{ Username }}"
        password: "{{ Password }}"
        dest: /tmp/Example-{{ ArtifactVersion }}.war
        mode: '0644'
    - name: Deploy in tomcat
      copy:
        src: /tmp/Example-0.0.1-SNAPSHOT.war
        dest: /opt/tomcat/webapps
        remote_src: yes
    - name: stop the tomcat
      shell: /opt/tomcat/bin/shutdown.sh
    - name: start the tomcat
      shell: /opt/tomcat/bin/startup.sh  
