- hosts: tomcat
  become: true
  vars:
    my_version: "{{ version }}"
  vars_files:
    - credential.yml
  tasks:
    - name: remove artifact file 
      shell: rm -rf /tmp/Example-0.0.4-SNAPSHOT.war
    - name: JFrogArtifactToHosttemp
      maven_artifact:
        group_id: com.github.Premvikash
        artifact_id: Example
        extension: war
        version: "{{ my_version }}"
        repository_url: "http://3.109.139.250:8081/artifactory/libs-snapshot-local/"
        username: "{{ username }}"
        password: "{{ password }}"
        dest: /tmp/Example-{{ my_version }}.war
        mode: '0644'
    - name: Deploy in tomcat
      copy:
        src: /tmp/Example-{{ my_version }}.war
        dest: /opt/tomcat/webapps
        remote_src: yes
       
    
