- hosts: tomcat
  become: true
  tasks:
    - name: check whether the war file exist
      stat:
        path: /tmp/Example-0.0.1-SNAPSHOT.war
      register: exist
    - name: remove war file from temp folder
      file:
        path: /tmp/Example-0.0.1.war
        state: absent
      when: exist.stat == True
    - name: JFrogArtifactToHosttemp
      maven_artifact:
        group_id: com.github.Premvikash
        artifact_id: Example
        extension: war
        version: 0.0.1-SNAPSHOT
        repository_url: "http://3.109.139.250:8081/artifactory/libs-snapshot-local/"
        username: admin
        password: admin123
        dest: /tmp/Example-0.0.1-SNAPSHOT.war
        mode: '0644'
    - name: Deploy in tomcat
      copy:
        src: /tmp/Example-0.0.1-SNAPSHOT.war
        dest: /opt/tomcat/webapps
        remote_src: yes
     
