- hosts: tomcat
  become: true
  vars_files:
    - credentials.var
  tasks:
    - name: remove artifact file 
      shell: rm -rf Example-0.0.2-SNAPSHOT.war
    - name: JFrogArtifactToHosttemp
      maven_artifact:
        group_id: com.github.Premvikash
        artifact_id: Example
        extension: war
        version: "{{ ArtifactVersion }}"
        repository_url: "http://3.109.139.250:8081/artifactory/libs-snapshot-local/"
        username: "{{ Username }}" 
        password: "{{ Password }}"
        dest: /tmp/"{{ ArtifactVersion }}".war
        mode: '0644'
    - name: Deploy in tomcat
      copy:
        src: /tmp/"{{ ArtifactVersion }}".war
        dest: /opt/tomcat/webapps
        remote_src: yes
    - name: stop the tomcat
      shell: /opt/tomcat/bin/shutdown.sh
    - name: start the tomcat
      shell: /opt/tomcat/bin/startup.sh  
